const AUTH_SERVER_PORT = 3005;
const SERVICES_SERVER_PORT = 3010;
const JWT_SECRET = 'jwtSecret';
const REDIS_TOKEN_EXPIRY = 3600 // in seconds
const MONGODB_PORT = 27017

module.exports = {
    AUTH_SERVER_PORT: AUTH_SERVER_PORT,
    SERVICES_SERVER_PORT: SERVICES_SERVER_PORT,
    JWT_SECRET: JWT_SECRET,
    REDIS_TOKEN_EXPIRY: REDIS_TOKEN_EXPIRY, // in seconds
    MONGODB_PORT: MONGODB_PORT
}